// Shared debrief copy + infographic config for all 13 battles.
// Used by showDebrief() in index.html.

export const DEBRIEF_DATA = {
  'Saragarhi': {
    epitaphWin:  'Twenty-one against ten thousand. The signal held until the last man.',
    epitaphLoss: 'They chose to stand. The walls did not.',
    eliminatedLabel: 'WAVES',
    infographic: {
      type: 'odds',
      indian: 21,
      enemy: '10,000',
      indianLabel: 'Sikh defenders',
      enemyLabel: 'Pashtun warriors',
      note: 'Held 7+ hours · 12 September 1897',
    },
    hero: {
      name: 'Havildar Ishar Singh',
      rank: 'Company Havildar Major, 36th Sikh',
      medal: 'Indian Order of Merit',
      quote: 'We will fight.',
    },
  },
  'Haifa': {
    epitaphWin:  'One of the last great cavalry charges. Haifa fell in under three hours.',
    epitaphLoss: 'The lances broke before the line.',
    eliminatedLabel: 'ROUTED',
    infographic: {
      type: 'charge',
      duration: '< 3 hours',
      prisoners: '1,350',
      guns: 17,
      note: '23 September 1918 · Ottoman Palestine',
    },
    hero: {
      name: 'Major Dalpat Singh',
      rank: 'Jodhpur Lancers',
      medal: 'Indian Order of Merit',
      quote: 'Lance levelled. Through the machine guns.',
    },
  },
  'Kohima': {
    epitaphWin:  'For your tomorrow, we gave our today.',
    epitaphLoss: 'The tennis court changed hands — but the line held in history.',
    eliminatedLabel: 'REPULSED',
    infographic: {
      type: 'siege',
      days: 15,
      garrison: '1,500',
      enemy: '15,000',
      note: 'Battle of the Tennis Court · April 1944',
    },
    hero: {
      name: 'The Kohima Epitaph',
      rank: 'Burma Campaign Memorial',
      medal: null,
      quote: 'When you go home, tell them of us and say — for your tomorrow, we gave our today.',
    },
  },
  'Rezang La': {
    epitaphWin:  'Frozen at their posts. Not one retreated.',
    epitaphLoss: 'C Company fell — but none retreated. Every man faced the enemy.',
    eliminatedLabel: 'PLA',
    infographic: {
      type: 'odds',
      indian: 114,
      enemy: 'Division',
      indianLabel: 'C Company, 13 Kumaon',
      enemyLabel: 'PLA 3rd Infantry',
      note: '−20°C · 16,000 ft · 18 November 1962',
    },
    hero: {
      name: 'Major Shaitan Singh',
      rank: 'OC, C Company, 13 Kumaon',
      medal: 'Param Vir Chakra — Posthumous',
      quote: 'Found facing the enemy. Wounded. He refused evacuation.',
    },
  },
  'Asal Uttar': {
    epitaphWin:  'Ninety-seven Pattons in the paddy. Patton Nagar.',
    epitaphLoss: 'The armour broke through the sector.',
    eliminatedLabel: 'PATTONS',
    infographic: {
      type: 'armour',
      destroyed: 97,
      label: 'Pakistani M48 Pattons',
      sub: 'Destroyed or captured at Khem Karan · September 1965',
    },
    hero: {
      name: 'CQMH Abdul Hamid',
      rank: '4 Grenadiers · Param Vir Chakra',
      medal: 'Param Vir Chakra — Posthumous',
      quote: 'Destroyed seven Patton tanks with his recoilless gun.',
    },
  },
  'Dograi': {
    epitaphWin:  'Fixed bayonets. No radio. Room to room in the dark.',
    epitaphLoss: 'The village held. The assault was repulsed.',
    eliminatedLabel: 'CLEARED',
    infographic: {
      type: 'timeline',
      start: '03:00',
      end: 'DAWN',
      label: 'Night assault · 21 September 1965',
      detail: '3 Jat Regiment · Lahore sector',
    },
    hero: {
      name: 'Lt Col Desmond Hayde',
      rank: '3 Jat Regiment · Maha Vir Chakra',
      medal: 'Maha Vir Chakra',
      quote: 'Led the assault personally when radios failed.',
    },
  },
  'Longewala': {
    epitaphWin:  'Hold until dawn. The Hunters are coming.',
    epitaphLoss: 'The post was overrun before first light.',
    eliminatedLabel: 'TANKS',
    infographic: {
      type: 'armour',
      destroyed: 36,
      label: 'Pakistani tanks destroyed',
      sub: '120 men held against 2,000 troops + 45 tanks · 5–6 Dec 1971',
    },
    hero: {
      name: 'Major Kuldeep Singh Chandpuri',
      rank: 'OC A Company, 23 Punjab',
      medal: 'Maha Vir Chakra',
      quote: 'Refused to withdraw. Held all night with small arms and mines.',
    },
  },
  'Siachen': {
    epitaphWin:  'Quaid Post became Bana Post. The glacier remembers.',
    epitaphLoss: 'The ice wall held. The assault failed.',
    eliminatedLabel: 'CLEARED',
    infographic: {
      type: 'altitude',
      peak: '21,153 ft',
      detail: '457m climb · 70° ice face',
      label: 'Bana Post — highest occupied post on earth',
    },
    hero: {
      name: 'Naib Subedar Bana Singh',
      rank: '19 JAK RIF',
      medal: 'Param Vir Chakra',
      quote: 'Stormed the bunker the world said was impregnable.',
    },
  },
  'Tololing': {
    epitaphWin:  'The first peak fell. The Tricolour at 16,962 ft.',
    epitaphLoss: 'The ridgeline held. The assault broke.',
    eliminatedLabel: 'NLI',
    infographic: {
      type: 'altitude',
      peak: '16,962 ft',
      detail: 'Night assault · near-vertical rock',
      label: 'First major Kargil peak retaken · 13 June 1999',
    },
    hero: {
      name: 'Major Vivek Gupta',
      rank: '2 Rajputana Rifles',
      medal: 'Maha Vir Chakra — Posthumous',
      quote: 'First to reach the ridge. Killed at the summit.',
    },
  },
  'Point 5140': {
    epitaphWin:  'Yeh dil maange more.',
    epitaphLoss: 'The ice face held them back.',
    eliminatedLabel: 'NLI',
    infographic: {
      type: 'altitude',
      peak: '5,140 m',
      detail: 'Night assault · Drass sector',
      label: 'Captured 20 June 1999 · Operation Vijay',
    },
    hero: {
      name: 'Captain Vikram Batra',
      rank: '13 JAK RIF · Call sign "Sher Shah"',
      medal: 'Param Vir Chakra — Posthumous',
      quote: 'Yeh Dil Maange More.',
    },
  },
  'Khalubar': {
    epitaphWin:  'Na chodnu. Do not spare them.',
    epitaphLoss: 'The bunker line held.',
    eliminatedLabel: 'BUNKERS',
    infographic: {
      type: 'altitude',
      peak: 'Point 4812',
      detail: '4 bunkers cleared alone',
      label: 'Batalik sector · 4 July 1999',
    },
    hero: {
      name: 'Captain Manoj Kumar Pandey',
      rank: '1/11 Gorkha Rifles',
      medal: 'Param Vir Chakra — Posthumous',
      quote: 'Na Chodnu. He was 25 years old.',
    },
  },
  'Tiger Hill': {
    epitaphWin:  'India holds the sky. Tiger Hill is ours.',
    epitaphLoss: 'The highest point remained in enemy hands.',
    eliminatedLabel: 'CLEARED',
    infographic: {
      type: 'altitude',
      peak: '5,060 m',
      detail: '1,500-ft cliff assault · Bofors support',
      label: 'Highest fortified position in the war · 4 July 1999',
    },
    hero: {
      name: 'Hav Yogendra Singh Yadav',
      rank: '18 Grenadiers',
      medal: 'Param Vir Chakra — Living',
      quote: 'Climbed the cliff on a rope. Shot multiple times. Kept climbing.',
    },
  },
  'Operation Sindoor': {
    epitaphWin:  'The radar stayed live. The skies held.',
    epitaphLoss: 'Airspace lost. The battery fell silent.',
    eliminatedLabel: 'DOWNED',
    infographic: {
      type: 'intercept',
      items: [
        { label: 'Drones',   inbound: 26, stopped: 24 },
        { label: 'Missiles', inbound: 8,  stopped: 7  },
        { label: 'Aircraft', inbound: 4,  stopped: 3  },
      ],
      note: 'Operation Bunyan-um-Marsoos · 10 May 2025',
    },
    hero: {
      name: 'S-400 Triumf Battery',
      rank: 'Army Air Defence Corps · Adampur',
      medal: 'First combat intercept',
      quote: 'India\'s layered air defence — S-400, Akash, MANPAD — held the line.',
    },
  },
};
