// Battle of Rezang La — 18 November 1962
// C Company, 13 Kumaon Regiment | 114 soldiers vs Chinese 3rd Infantry Division
export default {
  terrain: {
    'P': {color:0x1e1e30,height:3.8,block:true},
    'R': {color:0x2c2c42,height:3.0,block:true},
    'r': {color:0x5a5a6e,height:1.5,def:1.3,mov:2},
    's': {color:0x4a78b0,height:1.2,def:1.0,mov:1},
    'i': {color:0x8ac8e0,height:0.9,def:0.75,mov:2},
    '.': {color:0x7a6a52,height:1.0,def:1.0,mov:1},
  },
  map: [
    ['P','P','P','P','P','P','P','P','P','P','P'],
    ['P','P','R','s','s','s','s','R','P','P','P'],
    ['P','R','r','s','s','s','s','r','R','P','P'],
    ['P','R','r','.','s','.','s','.','r','R','P'],
    ['P','R','r','i','i','i','i','i','r','R','P'],
    ['P','R','r','.','i','.','i','.','r','R','P'],
    ['P','R','r','r','.','.','.','r','r','R','P'],
    ['P','R','r','r','.','.','.','r','r','R','P'],
    ['P','P','R','r','.','.','.','r','R','P','P'],
    ['P','P','P','P','.','.','.','P','P','P','P'],
  ],
  structures: {
    '4,6':{type:'lmg',  label:'LMG Nest',  atkMul:1.6,defMul:1.4,rngBonus:1},
    '6,6':{type:'lmg',  label:'LMG Nest',  atkMul:1.6,defMul:1.4,rngBonus:1},
    '5,8':{type:'mortar',label:'Mortar Pit',atkMul:2.0,defMul:1.0,rngBonus:2,noRetaliate:true},
    '3,7':{type:'sangar',label:'Sangar',    atkMul:1.0,defMul:1.8,rngBonus:0},
    '6,7':{type:'sangar',label:'Sangar',    atkMul:1.0,defMul:1.8,rngBonus:0},
  },
  indStarts: [
    {col:4,row:6,type:'section_cdr',name:'Nb Sub Dharam Paul', platoon:9,bio:'Commanded 9 Platoon forward. First to engage PLA at dawn.'},
    {col:5,row:6,type:'rifleman',   name:'Rfn Mool Singh',     platoon:9,bio:'Held center of the forward line. Fought until rounds were exhausted.'},
    {col:4,row:7,type:'section_cdr',name:'Hav Khem Chand',     platoon:9,bio:'Vir Chakra. Led hand-to-hand combat after ammunition ran out.'},
    {col:3,row:7,type:'section_cdr',name:'Hav Bhanwar Singh',  platoon:7,bio:'7 Platoon, western flank. Held ground under sustained fire.'},
    {col:3,row:8,type:'rifleman',   name:'Rfn Ram Kishan',     platoon:7,bio:'Left flank throughout. Never retreated.'},
    {col:6,row:7,type:'section_cdr',name:'Nb Sub Ram Kumar',   platoon:8,bio:'8 Platoon, eastern flank. Coordinated with HQ under fire.'},
    {col:6,row:8,type:'rifleman',   name:'Hav Hari Ram',       platoon:8,bio:'Continued firing after being wounded.'},
    {col:4,row:9,type:'hero',       name:'Maj Shaitan Singh',  platoon:0,bio:'Param Vir Chakra — Posthumous. Moved between positions under fire, rallying every section. Wounded but refused evacuation. Found facing the enemy.'},
    {col:5,row:9,type:'rifleman',   name:'Rfn Chuni Lal',      platoon:0,bio:'Sena Medal. Signaller. Kept radio contact with battalion HQ until the last.'},
  ],
  plaWaves: [
    [{col:3,type:'pla'},{col:5,type:'pla'},{col:6,type:'pla'}],
    [{col:3,type:'pla'},{col:4,type:'pla_cdr'},{col:5,type:'pla'},{col:6,type:'pla'}],
    [{col:3,type:'pla'},{col:4,type:'pla'},{col:5,type:'pla_cdr'},{col:6,type:'pla'},{col:3,type:'pla'}],
    [{col:3,type:'pla_cdr'},{col:4,type:'pla'},{col:5,type:'pla'},{col:6,type:'pla'},{col:4,type:'pla'},{col:6,type:'pla_cdr'}],
    [{col:3,type:'pla'},{col:4,type:'pla'},{col:5,type:'pla'},{col:6,type:'pla'},{col:3,type:'pla_cdr'},{col:5,type:'pla_cdr'},{col:6,type:'pla'}],
  ],
  initialEnemies: [],
  narratives: {
    1:  '18 Nov 1962 · 04:30 hrs — First contact. C Company stands to.',
    3:  'PLA artillery opens up across the pass.',
    5:  'Maj Shaitan Singh moves between positions, rallying each section under fire.',
    8:  'Ammunition running low. Soldiers fight hand to hand.',
    10: 'Last contact with battalion HQ. Every man faces the enemy.',
  },
  histCards: {
    1: {
      name:  'Major Shaitan Singh',
      rank:  'OC, C Company, 13 Kumaon Regiment',
      medal: 'Param Vir Chakra — Posthumous',
      body:  'At −20°C and 16,000 ft, he commanded 114 men of C Company against a PLA division. He moved between positions under artillery fire, rallying each section in turn. Wounded, he refused evacuation and continued directing his men. He was found facing the enemy.',
    },
    4: {
      name:  'Battle of Rezang La',
      rank:  '18 November 1962 · Historical Context',
      body:  '114 soldiers of C Company, 13 Kumaon held the Rezang La pass against the Chinese 3rd Infantry Division. 113 were killed in action; none retreated. Every man was found at his post, facing the enemy. The memorial at Rezang La reads: "How can a man die better than facing fearful odds."',
    },
    7: {
      name:  'Havildar Khem Chand',
      rank:  'Section Commander, 9 Platoon, 13 Kumaon',
      medal: 'Vir Chakra',
      body:  'When ammunition was exhausted, Khem Chand led his section in hand-to-hand combat with bayonets. He continued fighting after being wounded, refusing to leave his position. His platoon held the line to the last man.',
    },
  },
  winCondition:  {type:'waves'},
  defensiveAI:   false,
  enemyLabels:   {pla:'PLA Soldier', pla_cdr:'PLA Officer'},
  enemyBio:      'Chinese 3rd Infantry Division, Xinjiang Military Region.',
  introMeta:     '1962 · LADAKH · 16,000 FT',
  introText:     `C Company, 13 Kumaon — 114 soldiers defending Rezang La.<br>No artillery. No air support. −20°C and 16,000 ft above sea level.<br><br><strong style="color:#c8a96e;">HOW TO PLAY</strong><br>Click a green unit to select it.<br><span style="color:#4488ff;">Blue hexes</span> = movement range. &nbsp;<span style="color:#ff5555;">Red hexes</span> = attack range.<br>Each unit moves then attacks per turn. Enter or button to end turn.`,
  debriefWin:    'REZANG LA HELD',
  debriefLoss:   'C COMPANY FALLEN',
  debriefHistory:'In history, 113 of 114 Kumaon soldiers died at Rezang La. Not one retreated. Every man was found facing the enemy.',
  autoPlayForceWin: false,  // historical loss — all of C Company died
  autoPlayStyle: 'defensive',
};
